typography_spectrum: 0.2050968
color:
  saturation: 0.7481748
  lightness: 0.6134488
  brandStrength: 0.8420492
  rhythmicContrast: 0.6648888
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
layout_spectrum: 0.1534323
name: Unister
navigation:
  - name: Ãœbernahme
    id: afdca800-f7f0-49cd-aa26-00f548150d89
    type: content
  - name: Krimi
    id: d4195558-08b7-420e-a3a8-470e0055e8d5
    type: content
description: Press Clippings
